import type { Metadata } from "next";
import "./globals.css";
import Sidemenu from "@/components/layout/sidemenu";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="flex p-8 gap-14">
          <Sidemenu />
          {children}
        </div>
      </body>
    </html>
  );
}
